api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from api import views

app_name = 'api'

urlpatterns = [
    path('feed/detail/', views.FeedDetailView.as_view(), name='feed-detail'),
    path('feed/detail/no-auth/', views.FeedDetailAllowAnyView.as_view(), name='feed-detail-no-auth'),
    path('feed/detail/save/', views.FeedDetailSaveView.as_view(), name='feed-detail-save'),
    path('token/', obtain_auth_token, name='obtain-auth-token')
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('feed/<str:feed_id>/', views.feed_detail, name='feed-detail'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawler/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny

schema_view = get_schema_view(
   openapi.Info(
      title="Feed",
      default_version='v1',
      description="Feed de notícias",
      contact=openapi.Contact(email="guile.hm@hotmail.com"),
   ),
   public=True,
   permission_classes=(AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('api/', include('api.urls', namespace='api')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

core/models.py
import uuid

from django.db import models


class DataFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file = models.FileField(upload_to='core/datafile/file')

    date_added = models.DateTimeField(auto_now_add=True, db_index=True)
    date_changed = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-date_added', )

    def __str__(self):
        return f'{self.id}'

api/views.py
import json
import tempfile
import uuid

from django.core.files import File
from django.shortcuts import redirect
from requests.exceptions import RequestException
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from core.models import DataFile
from utils import create_feed


class FeedDetailView(APIView):
    permission_classes = (IsAuthenticated,)
    authentication_classes = (TokenAuthentication,)
    renderer_classes = (JSONRenderer,)

    def get(self, request, *args, **kwargs):
        status_code = HTTP_200_OK
        feed_data = None
        try:
            feed_data = create_feed()
        except RequestException:
            status_code = HTTP_400_BAD_REQUEST
        return Response(
            data=feed_data,
            status=status_code,
        )


class FeedDetailAllowAnyView(APIView):
    permission_classes = (AllowAny,)
    renderer_classes = (JSONRenderer,)

    def get(self, request, *args, **kwargs):
        status_code = HTTP_200_OK
        feed_data = None
        try:
            feed_data = create_feed()
        except RequestException:
            status_code = HTTP_400_BAD_REQUEST
        return Response(
            data=feed_data,
            status=status_code,
        )


class FeedDetailSaveView(APIView):
    permission_classes = (AllowAny,)
    renderer_classes = (JSONRenderer,)

    def get(self, request, *args, **kwargs):
        feed_data = None
        try:
            feed_data = create_feed()
        except RequestException:
            status_code = HTTP_400_BAD_REQUEST
            return Response(
                data=feed_data,
                status=status_code,
            )

        with tempfile.TemporaryFile() as file:
            file.write(
                json.dumps(feed_data, indent=4, separators=(',', ': '), ensure_ascii=False).encode('UTF-8')
            )
            file.seek(0)
            data_file = DataFile.objects.create(
                file=File(file, name='{name}.{extension}'.format(
                    name=str(uuid.uuid4()),
                    extension='json',
                ))
            )
        return redirect('core:feed-detail', feed_id=data_file.id)

core/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import redirect, render
from rest_framework.authtoken.models import Token

from core.models import DataFile


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            Token.objects.create(user=user)
            return redirect('core:index')
    else:
        form = UserCreationForm()
    return render(request, 'core/accounts/signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('core:index')


def login_view(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            authenticated_user = authenticate(
                username=request.POST['username'],
                password=request.POST['password']
            )
            login(request, authenticated_user)
            return redirect('core:index')
    return render(request, 'core/accounts/login.html', {
        'form': form,
    })


def index(request):
    return render(request, 'core/index.html')


def feed_detail(request, feed_id):
    feed = DataFile.objects.get(id=feed_id)
    return redirect(feed.file.url)

core/templates/core/accounts/login.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    {% language 'pt-BR' %}
    <div class="container text-center pt-5 my-5">
        <h1 class="display-2">login</h1>
        <p class="lead mt-3">
            faça aqui seu login
        </p>
    </div>
    <div class="container text-center">
        {% for error in form.non_field_errors %}
            <div class="negative-feedback mb-3">
                {{ error }}
            </div>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col-md-4 mb-3">
                    <label for="id_username">usuário</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="id_icon_username">@</span>
                        </div>
                        <input type="text" class="form-control" id="id_username" name="username" placeholder="usuário" aria-describedby="inputGroupPrepend3" required>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-4 mb-3">
                    <label for="id_username">senha</label>
                    <div class="input-group">
                        <input type="password" class="form-control" id="id_password" name="password" placeholder="senha" aria-describedby="inputGroupPrepend3" required>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-sm btn-primary">entrar</button>
        </form>
    </div>
    {% endlanguage %}
{% endblock %}

core/templates/core/accounts/signup.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    {% language 'pt-BR' %}
    <div class="container text-center pt-5 my-5">
        <h1 class="display-2">criar usuário</h1>
        <p class="lead mt-3">
            crie aqui seu usuário
        </p>
    </div>
    <div class="container text-center">
        {% for error in form.non_field_errors %}
            <div class="negative-feedback mb-3">
                {{ error }}
            </div>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col-md-4 mb-3">
                    <label for="id_username">usuário</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="id_icon_username">@</span>
                        </div>
                        <input type="text" class="form-control" id="id_username" name="username" placeholder="usuário" aria-describedby="inputGroupPrepend3" required>
                    </div>
                    {% for error in form.username.errors %}
                        <div class="negative-feedback mb-3">
                            <span class="text-danger">{{ error }}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-4 mb-3">
                    <label for="id_username">senha</label>
                    <div class="input-group">
                        <input type="password" class="form-control" id="id_password1" name="password1" placeholder="senha" aria-describedby="inputGroupPrepend3" required>
                    </div>
                    {% for error in form.password1.errors %}
                        <div class="negative-feedback mb-3">
                            <span class="text-danger">{{ error }}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-4 mb-3">
                    <label for="id_username">digite novamente a senha</label>
                    <div class="input-group">
                        <input type="password" class="form-control" id="id_password2" name="password2" placeholder="senha" aria-describedby="inputGroupPrepend3" required>
                    </div>
                    {% for error in form.password2.errors %}
                        <div class="negative-feedback mb-3">
                            <span class="text-danger">{{ error }}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <button type="submit" class="btn btn-sm btn-primary">entrar</button>
        </form>
    </div>
    {% endlanguage %}
{% endblock %}

core/templates/core/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block extra_header %}
    {% endblock %}

    <title>Feeds</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-link">
                        <a class="text-dark" href="{% url 'core:index' %}"><strong>home</strong></a>
                    </li>
                    {% if not request.user.is_authenticated %}
                        <li class="nav-link">
                            <a class="text-dark" href="{% url 'core:login' %}"><strong>login</strong></a>
                        </li>
                        <li class="nav-link">
                            <a class="text-dark" href="{% url 'core:signup' %}"><strong>cadastrar</strong></a>
                        </li>
                    {% else %}
                        <li class="nav-link">
                            <a class="text-dark" href="{% url 'core:logout' %}"><strong>logout</strong></a>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer border-top">
        <div class="text-center mt-3">desenvolvido por:
            <a href="https://github.com/Guilehm/"> guilherme luis</a>
        </div>
    </footer>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}
    <div class="container text-center py-5 my-5">
        <h1 class="display-2">Autoesporte Feed</h1>
        {% if request.user.is_authenticated %}
            <p class="lead mt-3">
                {% if request.user.first_name %}
                    olá, {{ request.user.first_name }}, seja bem-vindo!
                {% else %}
                    olá, {{ request.user.username }}, seja bem-vindo!
                {% endif %}
                <br>
                Encontre seu token de autenticação no endpoint <code>/api/token/</code> <br>
                <span>faça um POST passando "username" e "password" no corpo da solicitação</span>
            </p>
        {% else %}
            <p class="lead mt-3">
                faça login ou cadastre-se utilizar a API
            </p>
        {% endif %}
    </div>

    {% if request.user.is_authenticated %}
    <div class="container text-center pb-5 my-5">
        <h1 class="display-4">Requisições</h1>
        <p class="lead mt-3">
            Ao tentar acessar o endpoint <a class="text-danger" href="{% url 'api:feed-detail' %}" target="_blank"><code>/api/feed/detail/</code></a> sem informar o token, receberá a mensagem de que as credenciais não foram informadas
        </p>
        <p class="lead mt-3">
            Envie o token no headers neste formato: <br>
            <code>Authorization: Token {{ request.user.auth_token }}</code>
        </p>
        <h1 class="display-4 mt-4 pt-4">Endpoint sem Autenticação</h1>
        <p class="lead mt-3">
            Caso queira apenas visualizar a resposta em json, disponibilizei um endpoint que não exige autenticação.
            <a href="{% url 'api:feed-detail-no-auth' %}" target="_blank">link</a>
        </p>
        <h1 class="display-4 mt-4 pt-4">JSON Formatado</h1>
        <p class="lead mt-3">
            Para uma melhor visualização da resposta, acesse esse endpoint <code><a href="{% url 'api:feed-detail-save' %}" target="_blank">link</a></code>
        </p>
    </div>
    {% endif %}
{% endblock %}